# Sample workflow for building and deploying an Astro site to GitHub Pages
#
# To get started with Astro see: https://docs.astro.build/en/getting-started/
#
name: Checkout test

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
    paths:
      - src/**/*
      - package.json
      - astro.config.ts
      - panda.config.ts

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write

env:
  BUILD_PATH: "." # default value when not using subfolders
  # BUILD_PATH: subfolder
  CLONED_PATH: mdx-contents

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            echo "runner=yarn" >> $GITHUB_OUTPUT
            exit 0
          elif [ -f "${{ github.workspace }}/package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: ${{ steps.detect-package-manager.outputs.manager }}
          cache-dependency-path: ${{ env.BUILD_PATH }}/package-lock.json

      - name: Install dependencies
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
        working-directory: ${{ env.BUILD_PATH }}

      - name: Clone contents repository
        uses: actions/checkout@v4
        with:
          repository: cieloazul310/map310-contents
          path: ${{ env.CLONED_PATH }}
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Move to content collection
        run: |
          cp ${{ env.BUILD_PATH }}/src/content/config.ts ${{ env.CLONED_PATH }}/src
          rm -rf ${{ env.BUILD_PATH }}/src/content
          mv ${{ env.CLONED_PATH }}/src ${{ env.BUILD_PATH }}/src/content
          tree ${{ env.BUILD_PATH }}/src/content
        
        # ${{ steps.detect-package-manager.outputs.runner }} astro sync
  
      - name: Type checking
        run: |
          ${{ steps.detect-package-manager.outputs.runner }} astro check
        working-directory: ${{ env.BUILD_PATH }}
    
      - name: Build with Astro
        run: |
          ${{ steps.detect-package-manager.outputs.runner }} astro build --verbose
